In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import pylab as pl
import numpy as np
import keras

Using TensorFlow backend.
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:526: FutureWarn

In [11]:
df=pd.read_csv("FGData.csv",nrows=2076) #Taking first 2076 rows since they have more meaningful data
df.head()

Date  Hour  Minute   M1voltage  M1current  M1power  M1energy  \
0  13/05/15     0       1  230.127566        0.0      0.0  0.296908   
1  13/05/15     0       3  230.145109        0.0      0.0  0.296908   
2  13/05/15     0       4  230.156163        0.0      0.0  0.296908   
3  13/05/15     0       5  230.154073        0.0      0.0  0.296908   
4  13/05/15     0       6  230.187417        0.0      0.0  0.296908   

  M1waterconsumptionpm   M2voltage  M2current  ...  M3energy  \
0                    0  230.580605        0.0  ...  0.096054   
1                    0  230.605005        0.0  ...  0.096054   
2                    0  230.608336        0.0  ...  0.096054   
3                    0  230.603044        0.0  ...  0.096054   
4                    0  230.645034        0.0  ...  0.096054   

   M3waterconsumptionpm       Temp  Humid  Windspeed  Winddirec  Rainfall  \
0                   0.0  20.222222     93          0         33      0.28   
1                   0.0  20.222222     94          0         33      0.28   
2                   0.0  20.222222     94          0         33      0.28   
3                   0.0  20.222222     94          0         33      0.28   
4                   0.0  20.222222     94          0         33      0.28   

   Pressure  Radiation  Pm2.5  
0    27.963          0   49.6  
1    27.963          0   49.6  
2    27.966          0   49.6  
3    27.965          0   49.6  
4    27.966          0   49.6  

[5 rows x 26 columns]

In [23]:
cdf = df[['M1voltage','M1energy','M2voltage','M2energy','M3voltage','M3energy','Humid','Temp','Pressure','Pm2.5']]
cdf.head(10000)

M1voltage  M1energy   M2voltage  M2energy   M3voltage  M3energy  Humid  \
0     230.127566  0.296908  230.580605  2.484218  230.052971  0.096054     93   
1     230.145109  0.296908  230.605005  2.484218  230.084771  0.096054     94   
2     230.156163  0.296908  230.608336  2.484218  230.085489  0.096054     94   
3     230.154073  0.296908  230.603044  2.484218  230.080393  0.096054     94   
4     230.187417  0.296908  230.645034  2.484218  230.316635  0.096054     94   
...          ...       ...         ...       ...         ...       ...    ...   
2071  231.227227  0.489409  231.879227  4.687044  231.156506  0.251474     76   
2072  231.584082  0.489409  231.879227  4.687044  231.476602  0.251474     73   
2073  231.370748  0.489409  231.879227  4.687044  231.262773  0.251474     74   
2074  231.406247  0.489409  231.879227  4.687044  231.316028  0.251474     74   
2075    0.000000  0.000000  230.402784  1.556426  230.321457  0.291953     96   

           Temp  Pressure  Pm2.5  
0     20.222222    27.963   49.6  
1     20.222222    27.963   49.6  
2     20.222222    27.966   49.6  
3     20.222222    27.965   49.6  
4     20.222222    27.966   49.6  
...         ...       ...    ...  
2071  27.666667    27.983   49.6  
2072  27.722222    27.983   49.6  
2073  27.611111    27.983   49.6  
2074  27.666667    27.981   49.6  
2075  21.944444    27.901   49.7  

[2076 rows x 10 columns]

In [24]:
cdf.describe()

M1voltage     M1energy    M2voltage     M2energy    M3voltage  \
count  2076.000000  2076.000000  2076.000000  2076.000000  2076.000000   
mean    230.656836     0.375823   231.456139     3.453680   230.693527   
std       5.127949     0.084839     0.772691     0.928086     0.803388   
min       0.000000     0.000000   229.400251     1.556426   228.976638   
25%     230.126699     0.299522   230.839715     2.634063   230.054124   
50%     230.668182     0.321866   231.802608     3.026289   230.587719   
75%     231.214924     0.489409   231.879227     4.687044   231.133123   
max     233.480226     0.489409   233.945350     4.687044   233.397394   

          M3energy        Humid         Temp     Pressure        Pm2.5  
count  2076.000000  2076.000000  2076.000000  2076.000000  2076.000000  
mean      0.162937    90.920520    22.919744    27.957587    49.600048  
std       0.064350     5.004378     1.718580     0.034008     0.002195  
min       0.096054    73.000000    19.611111    27.882000    49.600000  
25%       0.115915    89.000000    22.722222    27.938000    49.600000  
50%       0.119838    92.000000    23.000000    27.957000    49.600000  
75%       0.250149    94.000000    23.555556    27.984000    49.600000  
max       0.291953    97.000000    28.222222    28.023000    49.700000

In [34]:
X = cdf.iloc[:,0:5].values
temppred = cdf.iloc[:,7].values

In [35]:
print(X)
print(temppred)

[[230.127566   0.296908 230.580605   2.484218 230.052971]
 [230.145109   0.296908 230.605005   2.484218 230.084771]
 [230.156163   0.296908 230.608336   2.484218 230.085489]
 ...
 [231.370748   0.489409 231.879227   4.687044 231.262773]
 [231.406247   0.489409 231.879227   4.687044 231.316028]
 [  0.         0.       230.402784   1.556426 230.321457]]
[20.222222 20.222222 20.222222 ... 27.611111 27.666667 21.944444]


In [36]:
#Normalizing data:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [37]:
from sklearn.neural_network import MLPRegressor

In [38]:
 clf = MLPRegressor(hidden_layer_sizes = (200, 100, 75, 50,25), activation = 'relu', solver = 'sgd', learning_rate = 'adaptive')

In [39]:
clf.fit(X,temppred)

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPRegressor(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
             beta_2=0.999, early_stopping=False, epsilon=1e-08,
             hidden_layer_sizes=(200, 100, 75, 50, 25),
             learning_rate='adaptive', learning_rate_init=0.001, max_fun=15000,
             max_iter=200, momentum=0.9, n_iter_no_change=10,
             nesterovs_momentum=True, power_t=0.5, random_state=None,
             shuffle=True, solver='sgd', tol=0.0001, validation_fraction=0.1,
             verbose=False, warm_start=False)

In [40]:
clf.score(X,temppred)

0.7585595608657936